/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceInput {
  'status' : AttendanceStatus,
  'regNo' : string,
}
export interface AttendanceRecord {
  'status' : AttendanceStatus,
  'date' : string,
  'dept' : string,
  'year' : bigint,
  'staffUsername' : string,
  'subjectId' : string,
  'regNo' : string,
}
export type AttendanceStatus = { 'present' : null } |
  { 'absent' : null } |
  { 'onDuty' : null };
export interface Subject { 'id' : string, 'name' : string }
export interface UserProfile { 'username' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAttendanceByStaff' : ActorMethod<
    [string, string, bigint],
    { 'ok' : Array<AttendanceRecord> } |
      { 'err' : string }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStudentAttendance' : ActorMethod<
    [string, string, bigint],
    Array<AttendanceRecord>
  >,
  'getSubjectsForDept' : ActorMethod<[string], Array<Subject>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<
    [string, string, string, Array<AttendanceInput>, string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSubjectsForDept' : ActorMethod<
    [string, string, Array<Subject>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'staffCreateAccount' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'staffLogin' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'staffLogout' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];