/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceInput {
  'status' : AttendanceStatus,
  'regNo' : RegistrationNumber,
}
export interface AttendanceRecord {
  'status' : AttendanceStatus,
  'date' : string,
  'staffUsername' : string,
  'subjectId' : SubjectId,
  'regNo' : RegistrationNumber,
}
export type AttendanceStatus = { 'present' : null } |
  { 'absent' : null };
export interface OverallAttendanceSummary {
  'name' : string,
  'overallPercentage' : number,
  'subjectSummaries' : Array<StudentAttendanceSummary>,
  'regNo' : RegistrationNumber,
}
export type RegistrationNumber = string;
export type SessionToken = string;
export interface Student {
  'name' : string,
  'registrationNumber' : RegistrationNumber,
}
export interface StudentAttendanceSummary {
  'totalClasses' : bigint,
  'subjectName' : string,
  'presentCount' : bigint,
  'absentCount' : bigint,
  'percentage' : number,
}
export interface Subject { 'id' : SubjectId, 'name' : string }
export type SubjectId = string;
export interface _SERVICE {
  'getAttendanceByStaff' : ActorMethod<[SessionToken], Array<AttendanceRecord>>,
  'getStudentAttendanceRecords' : ActorMethod<
    [RegistrationNumber],
    Array<AttendanceRecord>
  >,
  'getStudentAttendanceSummary' : ActorMethod<
    [RegistrationNumber],
    OverallAttendanceSummary
  >,
  'getStudents' : ActorMethod<[], Array<Student>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'initiateSeedData' : ActorMethod<[], undefined>,
  'login' : ActorMethod<[string, string], SessionToken>,
  'logout' : ActorMethod<[SessionToken], undefined>,
  'markAttendance' : ActorMethod<
    [SessionToken, SubjectId, string, Array<AttendanceInput>],
    undefined
  >,
  'resetAttendanceData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];