/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionToken = IDL.Text;
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const SubjectId = IDL.Text;
export const RegistrationNumber = IDL.Text;
export const AttendanceRecord = IDL.Record({
  'status' : AttendanceStatus,
  'date' : IDL.Text,
  'staffUsername' : IDL.Text,
  'subjectId' : SubjectId,
  'regNo' : RegistrationNumber,
});
export const StudentAttendanceSummary = IDL.Record({
  'totalClasses' : IDL.Nat,
  'subjectName' : IDL.Text,
  'presentCount' : IDL.Nat,
  'absentCount' : IDL.Nat,
  'percentage' : IDL.Float64,
});
export const OverallAttendanceSummary = IDL.Record({
  'name' : IDL.Text,
  'overallPercentage' : IDL.Float64,
  'subjectSummaries' : IDL.Vec(StudentAttendanceSummary),
  'regNo' : RegistrationNumber,
});
export const Student = IDL.Record({
  'name' : IDL.Text,
  'registrationNumber' : RegistrationNumber,
});
export const Subject = IDL.Record({ 'id' : SubjectId, 'name' : IDL.Text });
export const AttendanceInput = IDL.Record({
  'status' : AttendanceStatus,
  'regNo' : RegistrationNumber,
});

export const idlService = IDL.Service({
  'getAttendanceByStaff' : IDL.Func(
      [SessionToken],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getStudentAttendanceRecords' : IDL.Func(
      [RegistrationNumber],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getStudentAttendanceSummary' : IDL.Func(
      [RegistrationNumber],
      [OverallAttendanceSummary],
      ['query'],
    ),
  'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'initiateSeedData' : IDL.Func([], [], []),
  'login' : IDL.Func([IDL.Text, IDL.Text], [SessionToken], ['query']),
  'logout' : IDL.Func([SessionToken], [], []),
  'markAttendance' : IDL.Func(
      [SessionToken, SubjectId, IDL.Text, IDL.Vec(AttendanceInput)],
      [],
      [],
    ),
  'resetAttendanceData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionToken = IDL.Text;
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'absent' : IDL.Null,
  });
  const SubjectId = IDL.Text;
  const RegistrationNumber = IDL.Text;
  const AttendanceRecord = IDL.Record({
    'status' : AttendanceStatus,
    'date' : IDL.Text,
    'staffUsername' : IDL.Text,
    'subjectId' : SubjectId,
    'regNo' : RegistrationNumber,
  });
  const StudentAttendanceSummary = IDL.Record({
    'totalClasses' : IDL.Nat,
    'subjectName' : IDL.Text,
    'presentCount' : IDL.Nat,
    'absentCount' : IDL.Nat,
    'percentage' : IDL.Float64,
  });
  const OverallAttendanceSummary = IDL.Record({
    'name' : IDL.Text,
    'overallPercentage' : IDL.Float64,
    'subjectSummaries' : IDL.Vec(StudentAttendanceSummary),
    'regNo' : RegistrationNumber,
  });
  const Student = IDL.Record({
    'name' : IDL.Text,
    'registrationNumber' : RegistrationNumber,
  });
  const Subject = IDL.Record({ 'id' : SubjectId, 'name' : IDL.Text });
  const AttendanceInput = IDL.Record({
    'status' : AttendanceStatus,
    'regNo' : RegistrationNumber,
  });
  
  return IDL.Service({
    'getAttendanceByStaff' : IDL.Func(
        [SessionToken],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getStudentAttendanceRecords' : IDL.Func(
        [RegistrationNumber],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getStudentAttendanceSummary' : IDL.Func(
        [RegistrationNumber],
        [OverallAttendanceSummary],
        ['query'],
      ),
    'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'initiateSeedData' : IDL.Func([], [], []),
    'login' : IDL.Func([IDL.Text, IDL.Text], [SessionToken], ['query']),
    'logout' : IDL.Func([SessionToken], [], []),
    'markAttendance' : IDL.Func(
        [SessionToken, SubjectId, IDL.Text, IDL.Vec(AttendanceInput)],
        [],
        [],
      ),
    'resetAttendanceData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };