/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
  'onDuty' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'status' : AttendanceStatus,
  'date' : IDL.Text,
  'dept' : IDL.Text,
  'year' : IDL.Nat,
  'staffUsername' : IDL.Text,
  'subjectId' : IDL.Text,
  'regNo' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'role' : IDL.Text,
});
export const Subject = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const AttendanceInput = IDL.Record({
  'status' : AttendanceStatus,
  'regNo' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAttendanceByStaff' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(AttendanceRecord), 'err' : IDL.Text })],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStudentAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getSubjectsForDept' : IDL.Func([IDL.Text], [IDL.Vec(Subject)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(AttendanceInput),
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveSubjectsForDept' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(Subject)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'staffCreateAccount' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'staffLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'staffLogout' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'absent' : IDL.Null,
    'onDuty' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'status' : AttendanceStatus,
    'date' : IDL.Text,
    'dept' : IDL.Text,
    'year' : IDL.Nat,
    'staffUsername' : IDL.Text,
    'subjectId' : IDL.Text,
    'regNo' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'role' : IDL.Text });
  const Subject = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const AttendanceInput = IDL.Record({
    'status' : AttendanceStatus,
    'regNo' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAttendanceByStaff' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(AttendanceRecord), 'err' : IDL.Text })],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStudentAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getSubjectsForDept' : IDL.Func([IDL.Text], [IDL.Vec(Subject)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(AttendanceInput),
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveSubjectsForDept' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(Subject)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'staffCreateAccount' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'staffLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'staffLogout' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };